1. Sum of given "n" numbers

In [3]:
from functools import reduce
#input the integers
n= int(input())
#defining the function nsum that retunrs sum
def nsum(x,y):
    return int(x)+int(y)
#boundary condition check
if n>100 or n<=0:
    print(0)
else :
    numbers = input()
    nlist = numbers.split()
    #boundary condition check
    if n != len(nlist):
        print("Error")
        exit()
    #calling the nsum function
    summ = reduce(nsum, nlist)
    print(summ)

3
1 2 3
6


2. Find the second largest element in a list of integers

In [5]:
#input the String of numbers
input_str = input()
#split string to list of integers
int_list = list(map(int,input_str.split(',')))
#boundary condition checking
if(len(int_list) < 2 or len(int_list) > 100000):
    print("Error")
    exit()
#Sorting the list to extract max
sorted_list = sorted(int_list,reverse=True)
#Checking if the second max exists
if sorted_list.count(sorted_list[0]) == len(int_list):
    print("Error")
    exit()
#Creating new list without the max element
in_list_2 = [i for i in int_list if i != sorted_list[0]]
#Sorting the new list to get the second max
sorted_list = sorted(in_list_2,reverse=True)
print(sorted_list[0])

1,3,2
2


3. Fizz Buzz-11. Write a program that prints the numbers from 1 to n. For multiples of ‘3’ print “Fizz” instead of the number and for the multiples of ‘5’ print “Buzz” instead of the the number itself. If a number is a multiple of 3 and 5 both, print "FizzBuzz".

In [6]:
#input the range of numbers
num = int(input())
#check boundary condition
if(num < 1 or num > 10000):
    print("Error")
    exit()
#create list for the range of numbers
in_list = [i for i in range(num+1) if i != 0]
#defining function to replace the integers with string
def fizzbuzz(val):
    if val % 15 == 0:
        return 'FizzBuzz'
    if val % 5 == 0:
        return 'Buzz'
    if val % 3 == 0:
        return 'Fizz'
    return val
#calling map to create new list
fizz_list = list(map(fizzbuzz,in_list))
#print the list with comma separator
print(*fizz_list, sep =',') 

5
1,2,Fizz,4,Buzz


4. Climbing Stairs. 
   You are climbing a staircase. It takes "n" steps to reach the top.

   Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?

In [7]:
import math
#defining factorial function
def fact(n) :
    if n==0:
      return 1
    if n==1:
      return 1
    return n*fact(n-1)
#input number of steps
steps = int(input())
#check boundary condition
if steps > 30 or steps < 1 :
    print("Error")
#assigning the divisor and reminder of 2 to i and j
i = math.floor(steps / 2)
j = steps % 2
ways = 0
while True :
  if i < 0:
    break
  ways = ways + (fact(i+j)/(fact(i)*fact(j)))
  i = i - 1
  j = j + 2
print(int(ways))

21
17711


5. Find any of the peak elements
   A peak element is an element that is strictly greater than its neighbors.

   Given an integer array "a", find a peak element, and return its index.

   You may imagine that a[-1] = a[n] = -∞.

   Design a O(lg(n)) time & O(1) space algorithm.

   Sample Input :
   2,0,1,4,5,8,4

   Sample Output:
   5

In [9]:
a = list(map(int,input().split(",")))
peakflag = 0;
for i in range(1,len(a)-1):
  if((a[i] > a[i-1]) and (a[i] > a[i+1])) :
    peakflag = 1;
    print(i);
    break;
if(peakflag == 0):
    if(a[0] > a[len(a)-1]) :
      print(0)
    else :
      print(len(a)-1)

2,0,1,4,5,8,4
5


6. Longest Arithmetic subsequence.
   Given an array A of integers, return the length of the longest arithmetic    subsequence in A.

Recall that a subsequence of A is a list A[i_1], A[i_2], ..., A[i_k] with 0 <= i_1 < i_2 < ... < i_k <= A.length - 1, and that a sequence B is arithmetic if B[i+1] - B[i] are all the same value (for 0 <= i < B.length - 1).

Sample Input: 
2,4,6,8

Sample Output:
4

In [10]:
from collections import Counter

s = input().split(",")
a = [int(i) for i in s]
c = []
[c.append(x) for x in a if x not in c]
b = []
for i in range(0,len(c)-1) :
  for j in range(i+1,len(c)) :
    b.append(c[i] - c[j])
for element in c:
  if a.count(element) > 1:
    for i in range(a.count(element)-1) :
      b.append(0)
occurence_count = Counter(b);
print(abs(occurence_count.most_common(1)[0][1]) + 1)

2,4,6,8
4


7. Shape and Reshape
   The shape tool gives a tuple of array dimensions and can be used to change the dimensions of an array.
     Sample Input : 1 2 3 4 5 6 7 8 9
     Sample Output:
   [[1 2 3]
    [4 5 6]
    [7 8 9]]

In [11]:
import numpy
numbers = input()
nlist = numbers.split()
my_array = numpy.asarray(nlist,int)
print(numpy.reshape(my_array,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


8. Min and Max. 
   min
   The tool min returns the minimum value along a given axis.
   max
   The tool max returns the maximum value along a given axis.

In [12]:
import numpy
dim = list(map(int,input().split()))
o_arr = numpy.empty((0,dim[1]),int)
for i in range(dim[0]) :
  nlist = list(map(int,input().split()))
  o_arr = numpy.append(o_arr,[[nlist]])
o_arr = o_arr.reshape(dim[0],dim[1])
print(numpy.max(numpy.min(o_arr, axis = 1)))

4 3 2
3 4 5
1 2 3
2 3 4
1 2 3
3


9. Concatenate. Two or more arrays can be concatenated together using the concatenate function with a tuple of the arrays to be joined:

In [14]:
import numpy
N,M,P = list(map(int,input().split()))
n_arr = numpy.empty((0,P),int)
m_arr = numpy.empty((0,P),int)
for i in range(N) :
  nlist = list(map(int,input().split()))
  n_arr = numpy.append(n_arr,[[nlist]])
n_arr = n_arr.reshape(N,P)
for i in range(M) :
  nlist = list(map(int,input().split()))
  m_arr = numpy.append(m_arr,[[nlist]])
m_arr = m_arr.reshape(M,P)
print(numpy.concatenate((n_arr, m_arr), axis = 0) )

2 2 2
1 2
2 3
3 4
3 4
[[1 2]
 [2 3]
 [3 4]
 [3 4]]


10. Eye and Identity. The identity tool returns an identity array. An identity array is a square matrix with all the main diagonal elements as  and the rest as . The default type of elements is float.

In [16]:
import numpy
numpy.set_printoptions(legacy = '1.13')
N,M = list(map(int,input().split()))
print(numpy.eye(N, M, k = 0))

3 4
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]


11. Dot and Cross. 
    The dot tool returns the dot product of two arrays.
    The cross tool returns the cross product of two arrays.

In [17]:
import numpy
N = int(input())
A = numpy.empty((0,N),int)
B = numpy.empty((0,N),int)
for i in range(N) :
  nlist = list(map(int,input().split()))
  A = numpy.append(A,[[nlist]])
A = A.reshape(N,N)
for i in range(N) :
  nlist = list(map(int,input().split()))
  B = numpy.append(B,[[nlist]])
B = B.reshape(N,N)

print(numpy.dot(A,B))

2
1 2
3 4
1 3
2  4
[[ 5 11]
 [11 25]]


In [18]:
import numpy
N = int(input())
A = numpy.empty((0,N),int)
B = numpy.empty((0,N),int)
C = numpy.empty((N,N),int)
D = numpy.empty((N,N),int)

for i in range(N) :
  nlist = list(map(int,input().split()))
  A = numpy.append(A,[[nlist]])
A = A.reshape(N,N)
for i in range(N) :
  nlist = list(map(int,input().split()))
  B = numpy.append(B,[[nlist]])
B = B.reshape(N,N)
for i in range(N) :
    for j in range(N) :
      C[i-1][j-1] = B[j-1][i-1]
for i in range(N) :
    for j in range(N) :
      D[i-1][j-1] = numpy.dot(A[i-1],C[j-1])
print(D)

2
1 2
3 4
1 4
2 4
[[ 5 12]
 [11 28]]


12. Find a real valued "x" such that x^5 - x^4 + 2*x^3 - x^2 + x = 3. Print the result to 5 decimal places of accuracy

In [19]:
import math
def f(x):
    return x**5 - x**4 + 2*x**3 - x**2 + x - 3;
x_l =0;
x_u =1;
while(True) :
  if ((f(x_l) < 0) and (f(x_u) > 0)):
    break;
  if ((f(x_l) < 0) and (f(x_u) < 0)):
    x_l = x_l+1;
    x_u = x_u+1;
  if ((f(x_l) > 0) and (f(x_u) > 0)):
    x_l = x_l-1;
    x_u = x_u-1;
x = (x_u + x_l)/ 2;
#iterate
while (abs(f(x)) > 0.00001): # till we are very close to zero   
    x = (x_u + x_l)/ 2;
    if f(x) > 0: # adjust x_l
        x_u = x;
    else: # adjust x_u
        x_l = x; 
print("%0.5f" % x)

1.13555


13. Area between curves.Compute the area between curves x^3 and e^x for x in the range +0 and +4 Note that curves these intersect in this region. To plot them using Google Search, just type: "plot (e^x) and (x^3)"

In [21]:
import math
import numpy
def epowerx(x):
  return math.exp(x)

def xpower3(x):
  return x**3
Area = 0
step = 0.001
for i in numpy.arange(0,4,step):
  Axpower3 = ((xpower3(i) + xpower3(i+step))*step)/2;
  Aepowerx = ((epowerx(i) + epowerx(i+step))*step)/2;
  Area = Area + abs(Aepowerx - Axpower3);
print(Area)

15.2649373022


14. Implement basic metrics in Stats from scratch

In [22]:
import numpy as np
import math
#numbs = [1,2,3,3,4,4,5,5,5,7,8,6]
numbs = [90, 65, 72, 48, 94, 90, 46, 65, 87, 56, 1, 2, 3, 4, 5, 6, 6, 7, 8, 9]
mean = np.sum(numbs)/len(numbs)
print("Mean :",np.mean(numbs))
print("Custom Mean :",mean)
if len(numbs)%2 == 0:
  median = (np.sort(numbs)[len(numbs)//2 -1] + np.sort(numbs)[len(numbs)//2])/2
else:
  median = np.sort(numbs)[len(numbs)//2]
print("Median :",np.median(numbs))
print("Custom Median :",median)
var = (1/len(numbs))*(np.sum([(x - mean) ** 2 for x in numbs]))
print("Variance :",np.var(numbs))
print("Custom Variance :",var)
std_dev = math.sqrt(var)
print("Standard Deviation   :",np.std(numbs))
print("Custom Standard Deviation   :",std_dev)
mad = (1/len(numbs))*(np.sum([abs(x - mean) for x in numbs]))
print("Mean Absolute Deviation:",np.mean(abs(numbs - np.mean(numbs))))
print("Custom Mean Absolute Deviation:",mad)
perc_75_index = (len(numbs)) * 75 / 100.0
perc_75 = np.sort(numbs)[int(math.ceil(perc_75_index)) - 1]
perc_25_index = (len(numbs)) * 25 / 100.0
perc_25 = np.sort(numbs)[int(math.ceil(perc_25_index)) - 1]
IQR = perc_75 - perc_25
print("IQR :",np.percentile(np.sort(numbs),75) - np.percentile(np.sort(numbs),25))
print("Custom IQR :",IQR)
perc_90_index = (len(numbs)) * 90 / 100.0
perc_90 = np.sort(numbs)[int(math.ceil(perc_90_index)) - 1]
print("90th percentile :",np.percentile(np.sort(numbs),90))
print("Custom 90th percentile :",perc_90)
perc_99_index = (len(numbs)) * 99 / 100.0
perc_99 = np.sort(numbs)[int(math.ceil(perc_99_index)) - 1]
print("99th percentile :",np.percentile(np.sort(numbs),99))
print("Custom 99th percentile :",perc_99)

Mean : 38.2
Custom Mean : 38.2
Median : 27.5
Custom Median : 27.5
Variance : 1246.56
Custom Variance : 1246.56
Standard Deviation   : 35.3066565962
Custom Standard Deviation   : 35.30665659617178
Mean Absolute Deviation: 33.1
Custom Mean Absolute Deviation: 33.1
IQR : 61.0
Custom IQR : 60
90th percentile : 90.0
Custom 90th percentile : 90
99th percentile : 93.24
Custom 99th percentile : 94
